- hosts: localhost
  connection: local
  vars:
    php_version: '7.4'
    php_default_version_debian: '7.4'

    roundcube_version: 1.4.8

  tasks:
    
    - name: Check the version of release
      command: hostnamectl
      register: os_check
      ignore_errors: yes

    -   name: Update apt cache.
        apt: update_cache=yes cache_valid_time=600
        when: ansible_os_family == 'Debian'

    -   name: Install dependencies.
        package:
            name:
                - curl
                - unzip
                - sendmail

    - name: Fetch Roundcube Role
      git:
        repo: https://ro:4RkyMP3MG9_JJYcpAxUf@pwslab.org/ansible/roundcube-playbook.git
        dest: /root/.ansible/roles/pwslab.roundcube
        version: master
        force: yes
    
    - name: Install Role Apache
      local_action: command ansible-galaxy install -f geerlingguy.apache 

    - name: Install Role MYSQL
      local_action: command ansible-galaxy install -f geerlingguy.mysql

    - name: Install Role PHP
      local_action: command ansible-galaxy install -f geerlingguy.php

    - name: Install Role REMI
      local_action: command ansible-galaxy install -f geerlingguy.repo-remi 

    - name: Install Role PHP-VERSIONS
      local_action: command ansible-galaxy install -f geerlingguy.php-versions

    - name: Check if Apache is already installed
      stat: path=/usr/sbin/httpd
      register: apache_exists

    - name: Check if PHP is already installed
      stat: path=/usr/bin/php
      register: php_exists

    - name: Check if MYSQL is already installed
      stat: path=/usr/bin/mysql
      register: mysql_exists

    - name: Applying role Apache
      command: mv ~/.ansible/roles/geerlingguy.apache ~/.ansible/roles/pwslab.apache
      when: not apache_exists.stat.exists
      ignore_errors: yes

    - name: Applying role PHP
      command: mv ~/.ansible/roles/geerlingguy.php ~/.ansible/roles/pwslab.php
      when: not php_exists.stat.exists
      ignore_errors: yes

    - name: Applying role REMI
      command: mv ~/.ansible/roles/geerlingguy.repo-remi  ~/.ansible/roles/pwslab.repo-remi 
      when: not php_exists.stat.exists
      ignore_errors: yes

    - name: Applying role PHP-Versions
      command: mv ~/.ansible/roles/geerlingguy.php-versions ~/.ansible/roles/pwslab.php-versions
      when: not php_exists.stat.exists
      ignore_errors: yes

    - name: Applying role MYSQL
      command: mv ~/.ansible/roles/geerlingguy.mysql ~/.ansible/roles/pwslab.mysql
      when: not mysql_exists.stat.exists
      ignore_errors: yes

    - name: Applying replacement on CentOS
      lineinfile:
          dest: ~/.ansible/roles/pwslab.php/vars/Debian.yml
          regexp: '^__php_webserver_daemon: '
          line: '__php_webserver_daemon: "httpd"'
          state: present
      when:
        - os_check.stdout | regex_search("CentOS")
    
    - name: Applying replacement on Ubuntu
      lineinfile:
          dest: ~/.ansible/roles/pwslab.php/vars/Debian.yml
          regexp: '^__php_webserver_daemon: '
          line: '__php_webserver_daemon: "apache2"'
          state: present
      when:
        - os_check.stdout | regex_search("Ubuntu")

    - name: Installing Apache
      include_role:
        name: pwslab.apache
      when: not apache_exists.stat.exists
    
    - name: Installing MYSQL
      include_role:
          name: pwslab.mysql
      when: not mysql_exists.stat.exists

    - name: Installing Remi
      include_role:
          name: pwslab.repo-remi 
      when: os_check.stdout | regex_search("CentOS")

    - name: Installing PHP-Versions
      include_role:
          name: pwslab.php-versions
      when: 
        - not php_exists.stat.exists
        - not os_check.stdout | regex_search("CentOS Linux release 8")
    
    - name: Installing PHP
      include_role:
          name: pwslab.php
      when: not php_exists.stat.exists

    - name: Installing Roundcube
      include_role:
        name: pwslab.roundcube
    
    