---

    -   name: Create schema for roundcube
        shell: mysql -u root -p'root' -e "CREATE SCHEMA roundcube DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"

    -   name: Create DB User roundcube
        shell: mysql -u root -p'root' -e "CREATE USER 'roundcube'@'localhost' IDENTIFIED BY 'roundcube';"

    -   name: Grant Privs to User roundcube
        shell: mysql -u root -p'root' -e "GRANT ALL PRIVILEGES ON roundcube.* TO 'roundcube'@'localhost';"
    
    -   name: Alter Privs to User roundcube
        shell: mysql -u root -p'root' -e "ALTER USER roundcube@'localhost' IDENTIFIED WITH mysql_native_password BY 'roundcube';"
        when:
            - os_check.stdout | regex_search("Ubuntu 20")

    # -   name: Create Roundcube Directory
    #     file:
    #         path: /var/www/html/roundcube
    #         state: directory
            # recurse: yes
            # owner: www-data
            # mode: '0755'

    -   name: Download Roundcube
        get_url:
            url: https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz
            dest: /tmp
        when:
            - os_check.stdout | regex_search("Ubuntu") or os_check.stdout | regex_search("CentOS")


    -   name: Extract Roundcube into /tmp
        unarchive:
            src: /tmp/roundcubemail-{{ roundcube_version }}-complete.tar.gz
            dest: /tmp/
        when:
            - os_check.stdout | regex_search("Ubuntu") or os_check.stdout | regex_search("CentOS")


    -   name: Move the Repos Around
        command: 
             mv /tmp/roundcubemail-{{ roundcube_version }} /var/www/html/roundcube
        ignore_errors: yes
        when:
            - os_check.stdout | regex_search("Ubuntu") or os_check.stdout | regex_search("CentOS")
    
    -   name: Grant Permissions
        file:
            path: /var/www/html/roundcube
            recurse: yes
            owner: www-data
            mode: '0775'
        when:
            - os_check.stdout | regex_search("Ubuntu") 

    -   name: Grant Permissions
        file:
            path: /var/www/html/roundcube
            recurse: yes
            owner: apache
            mode: '0775'
        when:
            - os_check.stdout | regex_search("CentOS")

    -   name: Import Schema
        shell: mysql -u roundcube -p'roundcube' roundcube < /var/www/html/roundcube/SQL/mysql.initial.sql
        

    # -   name: Copy files
    #     copy:
    #         src: /var/www/html/roundcube/config-dist.php
    #         dest: /var/www/html/roundcube/config.php
    #         owner: www-data
    #         group: www-data
    #         mode: '0777'
    #     when:
    #         - os_check.stdout | regex_search("Ubuntu") 

    # -   name: Copy files
    #     copy:
    #         src: /var/www/html/roundcube/admin/config-dist.php
    #         dest: /var/www/html/roundcube/admin/config.php
    #         owner: www-data
    #         group: www-data
    #         mode: '0777'
    #     when:
    #         - os_check.stdout | regex_search("Ubuntu") 

    
    # -   name: Copy files
    #     copy:
    #         src: /var/www/html/roundcube/config-dist.php
    #         dest: /var/www/html/roundcube/config.php
    #         owner: apache
    #         group: apache
    #         mode: '0777'
    #     when:
    #         - os_check.stdout | regex_search("CentOS") 

    # -   name: Copy files
    #     copy:
    #         src: /var/www/html/roundcube/admin/config-dist.php
    #         dest: /var/www/html/roundcube/admin/config.php
    #         owner: apache
    #         group: apache
    #         mode: '0777'
    #     when:
    #         - os_check.stdout | regex_search("CentOS") 

    -   name: Sets Apache conf file - Ubuntu
        become: true
        template:
            src: "roundcube.conf.j2"
            dest: "/etc/apache2/sites-available/roundcube.conf"
        when:
                - os_check.stdout | regex_search("Ubuntu")

    -   name: Disable default config
        command: a2ensite roundcube.conf
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Disable default config
        command: a2dissite 000-default.conf
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Install PHP Packages
        apt: 
            name: "{{ item }}" 
            update_cache: yes 
            state: present
        loop: 
            - php-cli
            - php-common
            - php-mbstring
            - php-gd
            - php-intl
            - php-xml
            - php-mysql
            - php-zip
            - php-curl
            - php-xmlrpc
            - libapache2-mod-php
            - php-gd
            - php-zip
            - php-curl
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Restart Apache
        service:
            name: apache2
            state: restarted
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Sets Apache conf file - CentOS
        become: true
        template:
            src: "roundcube.conf.j2"
            dest: "/etc/httpd/conf.d/roundcube.conf"
        when:
                - os_check.stdout | regex_search("CentOS")

    -   name: Install PHP Packages
        yum: 
            name: "{{ item }}" 
            update_cache: yes 
            state: present
        loop: 
            - php-mcrypt
            - curl
            - zlib
            - php-gd
            - php-mbstring
            - php-xml
            - php-mysql
            - php-zip   
        when:
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Enable remi repo - CentOS 7
        command: yum-config-manager --enable remi-php74
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Install PHP Packages
        yum: 
            name: "{{ item }}" 
            update_cache: yes 
            state: present
        loop: 
            - curl
            - zlib
            - php-gd
            - php-mbstring
            - php-xml
            - php-zip
            - php-pdo_mysql
        when:
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Restart Apache
        service:
            name: httpd
            state: restarted
        when:
            - os_check.stdout | regex_search("CentOS")

    -   name: Granting Permissions
        file:
            path: /var/www/html/roundcube
            recurse: yes
            owner: www-data
            mode: '0777'
        when:
            - os_check.stdout | regex_search("Ubuntu") 

    -   name: Granting Permissions
        file:
            path: /var/www/html/roundcube
            recurse: yes
            owner: apache
            mode: '0777'
        when:
            - os_check.stdout | regex_search("CentOS") 

    -   name: Disable SELinux
        selinux:
            state: disabled
        when:
            - os_check.stdout | regex_search("CentOS") 